# Form implementation generated from reading ui file 'createacc.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(341, 342)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(120, 20, 141, 41))
        self.label.setStyleSheet("font-size:20pt;\n"
"font-weight:bold")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 101, 31))
        self.label_2.setStyleSheet("font-size:13pt")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 101, 31))
        self.label_3.setStyleSheet("font-size:13pt")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 131, 31))
        self.label_4.setStyleSheet("font-size:13pt")
        self.label_4.setObjectName("label_4")
        self.email = QtWidgets.QLineEdit(parent=Dialog)
        self.email.setGeometry(QtCore.QRect(120, 80, 201, 41))
        self.email.setStyleSheet("font-size:12pt")
        self.email.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=Dialog)
        self.password.setGeometry(QtCore.QRect(120, 130, 201, 41))
        self.password.setStyleSheet("font-size:12pt")
        self.password.setObjectName("password")
        self.confirmpass = QtWidgets.QLineEdit(parent=Dialog)
        self.confirmpass.setGeometry(QtCore.QRect(150, 180, 171, 41))
        self.confirmpass.setStyleSheet("font-size:12pt")
        self.confirmpass.setObjectName("confirmpass")
        self.signupbutton = QtWidgets.QPushButton(parent=Dialog)
        self.signupbutton.setGeometry(QtCore.QRect(120, 270, 91, 41))
        self.signupbutton.setStyleSheet("font-size:14pt;\n"
"background-color:LimeGreen\n"
"")
        self.signupbutton.setObjectName("signupbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign up"))
        self.label_2.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.label_4.setText(_translate("Dialog", "Confirm Pass"))
        self.signupbutton.setText(_translate("Dialog", "Sign up"))
