# Form implementation generated from reading ui file 'crossover.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 475)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 391, 41))
        self.label.setStyleSheet("font-weight:bold;\n"
"font-size:20pt")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(0, 50, 701, 431))
        self.frame.setStyleSheet("background-color:rgba(44,55,68,255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 151, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142114.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(370, 0, 151, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142121.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(110, 210, 151, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142132.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(370, 210, 151, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142140.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 115, 151, 21))
        self.label_6.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(370, 115, 181, 21))
        self.label_7.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(110, 325, 191, 21))
        self.label_8.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(370, 325, 191, 21))
        self.label_9.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_9.setObjectName("label_9")
        self.Book = QtWidgets.QPushButton(parent=self.frame)
        self.Book.setGeometry(QtCore.QRect(110, 170, 141, 31))
        self.Book.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book.setObjectName("Book")
        self.Book2 = QtWidgets.QPushButton(parent=self.frame)
        self.Book2.setGeometry(QtCore.QRect(370, 170, 141, 31))
        self.Book2.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book2.setObjectName("Book2")
        self.Book3 = QtWidgets.QPushButton(parent=self.frame)
        self.Book3.setGeometry(QtCore.QRect(110, 380, 141, 31))
        self.Book3.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book3.setObjectName("Book3")
        self.Book4 = QtWidgets.QPushButton(parent=self.frame)
        self.Book4.setGeometry(QtCore.QRect(370, 380, 141, 31))
        self.Book4.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book4.setObjectName("Book4")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(110, 145, 161, 21))
        self.label_10.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(110, 350, 201, 21))
        self.label_11.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(370, 350, 221, 21))
        self.label_12.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(370, 140, 191, 21))
        self.label_13.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Crossover"))
        self.label.setText(_translate("Dialog", "The list of Crossover:"))
        self.label_6.setText(_translate("Dialog", "Toyota Rav 4"))
        self.label_7.setText(_translate("Dialog", "Subaru Forester"))
        self.label_8.setText(_translate("Dialog", "KIA Seltos 2024"))
        self.label_9.setText(_translate("Dialog", "Lexus RX330"))
        self.Book.setText(_translate("Dialog", "Book"))
        self.Book2.setText(_translate("Dialog", "Book"))
        self.Book3.setText(_translate("Dialog", "Book"))
        self.Book4.setText(_translate("Dialog", "Book"))
        self.label_10.setText(_translate("Dialog", "3600-4500 KGS"))
        self.label_11.setText(_translate("Dialog", "4000-5000 KGS"))
        self.label_12.setText(_translate("Dialog", "3600-4500 KGS"))
        self.label_13.setText(_translate("Dialog", "4400-5500 KGS"))
