# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(363, 368)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(130, 30, 101, 41))
        self.label.setStyleSheet("font-size:20pt;\n"
"font-weight:bold")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 91, 31))
        self.label_2.setStyleSheet("font-size:13pt")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 101, 31))
        self.label_3.setStyleSheet("font-size:13pt")
        self.label_3.setObjectName("label_3")
        self.email = QtWidgets.QLineEdit(parent=Dialog)
        self.email.setGeometry(QtCore.QRect(120, 90, 221, 41))
        self.email.setStyleSheet("font-size:12pt")
        self.email.setText("")
        self.email.setObjectName("username")
        self.password = QtWidgets.QLineEdit(parent=Dialog)
        self.password.setGeometry(QtCore.QRect(120, 150, 221, 41))
        self.password.setStyleSheet("font-size:12pt")
        self.password.setObjectName("password")
        self.loginbutton = QtWidgets.QPushButton(parent=Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(130, 270, 91, 41))
        self.loginbutton.setStyleSheet("font-size:14pt;\n"
"background-color:LimeGreen\n"
"")
        self.loginbutton.setObjectName("loginbutton")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(80, 230, 121, 16))
        self.label_4.setObjectName("label_4")
        self.createaccbutton = QtWidgets.QPushButton(parent=Dialog)
        self.createaccbutton.setGeometry(QtCore.QRect(200, 230, 61, 16))
        self.createaccbutton.setStyleSheet("background-color:SteelBlue")
        self.createaccbutton.setObjectName("createaccbutton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "Username"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.loginbutton.setText(_translate("Dialog", "Login"))
        self.label_4.setText(_translate("Dialog", "Don\'t have account?"))
        self.createaccbutton.setText(_translate("Dialog", "Create"))
