# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 585)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMaximumSize(QtCore.QSize(800, 500))
        self.centralwidget.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 70, 221, 391))
        self.frame.setStyleSheet("background-color:rgba(53,53,53,255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Book = QtWidgets.QPushButton(parent=self.frame)
        self.Book.setGeometry(QtCore.QRect(10, 310, 200, 35))
        self.Book.setStyleSheet("background-color:Red;\n"
"font-size:15pt;\n"
"border-radius:7px\n"
"")
        self.Book.setObjectName("Book")
        self.ksdds = QtWidgets.QComboBox(parent=self.frame)
        self.ksdds.setGeometry(QtCore.QRect(10, 70, 200, 25))
        self.ksdds.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.ksdds.setObjectName("ksdds")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/pin_drop_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.ksdds.addItem(icon, "")
        self.ksdds.addItem("")
        self.ksdds.addItem("")
        self.ksdds.addItem("")
        self.ksdds.setItemText(3, "")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setGeometry(QtCore.QRect(10, 40, 200, 25))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.comboBox.setEditable(False)
        self.comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertPolicy.InsertAlphabetically)
        self.comboBox.setMinimumContentsLength(6)
        self.comboBox.setObjectName("comboBox")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icons/directions_car_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBox.addItem(icon1, "")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 140, 200, 25))
        self.comboBox_2.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem(icon, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(parent=self.frame)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(10, 100, 201, 31))
        self.dateTimeEdit_2.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.dateTimeEdit_2.setFrame(True)
        self.dateTimeEdit_2.setCurrentSectionIndex(0)
        self.dateTimeEdit_2.setTimeSpec(QtCore.Qt.TimeSpec.LocalTime)
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(parent=self.frame)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(10, 170, 201, 31))
        self.dateTimeEdit_3.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.frame_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(240, 120, 541, 341))
        self.frame_2.setStyleSheet("background-color:rgba(53,53,53,255)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_2)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 541, 311))
        self.frame_4.setStyleSheet("background-color:rgba(44,55,68,255)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_2.setGeometry(QtCore.QRect(0, 50, 161, 141))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../../Снимок экрана 2025-04-10 102825.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(170, 50, 161, 141))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-10 103833.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_5.setGeometry(QtCore.QRect(340, 50, 161, 141))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-10 104041.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 511, 50))
        self.label_3.setStyleSheet("color:white;\n"
"font-size:19pt;\n"
"font-weight:bold\n"
"\n"
"")
        self.label_3.setObjectName("label_3")
        self.Sedan = QtWidgets.QPushButton(parent=self.frame_4)
        self.Sedan.setGeometry(QtCore.QRect(10, 200, 150, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Sedan.sizePolicy().hasHeightForWidth())
        self.Sedan.setSizePolicy(sizePolicy)
        self.Sedan.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 13pt;\n"
"color: black;\n"
"")
        self.Sedan.setObjectName("Sedan")
        self.Crossover = QtWidgets.QPushButton(parent=self.frame_4)
        self.Crossover.setGeometry(QtCore.QRect(170, 200, 150, 31))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Crossover.sizePolicy().hasHeightForWidth())
        self.Crossover.setSizePolicy(sizePolicy)
        self.Crossover.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 13pt;\n"
"color: black;\n"
"")
        self.Crossover.setObjectName("Crossover")
        self.SUV = QtWidgets.QPushButton(parent=self.frame_4)
        self.SUV.setGeometry(QtCore.QRect(340, 200, 150, 31))
        self.SUV.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 13pt;\n"
"color: black;\n"
"")
        self.SUV.setObjectName("SUV")
        self.label_6 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(20, 240, 91, 31))
        self.label_6.setStyleSheet("font-size:12pt;\n"
"color:white;\n"
"")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_7.setGeometry(QtCore.QRect(170, 240, 161, 31))
        self.label_7.setStyleSheet("font-size:12pt;\n"
"color:white")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame_4)
        self.label_8.setGeometry(QtCore.QRect(340, 240, 131, 31))
        self.label_8.setStyleSheet("font-size:12pt;\n"
"color:white")
        self.label_8.setObjectName("label_8")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(240, 70, 541, 41))
        self.label.setStyleSheet("color:black;\n"
"font-weight:bold;\n"
"font-size:23pt;\n"
"\n"
"")
        self.label.setObjectName("label")
        self.welcomeLabel= QtWidgets.QFrame(parent=self.centralwidget)
        self.welcomeLabel.setGeometry(QtCore.QRect(0, 0, 781, 41))
        self.welcomeLabel.setStyleSheet("background-color:DimGray")
        self.welcomeLabel.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.welcomeLabel.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.welcomeLabel.setObjectName("welcomeLabel\n"
"")
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.welcomeLabel
)
        self.pushButton_6.setGeometry(QtCore.QRect(380, 10, 201, 24))
        self.pushButton_6.setStyleSheet("color:white;\n"
"font-size:15pt;\n"
"border-radius:7px")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icons/call_24dp_FFFFFF_FILL0_wght400_GRAD0_opsz24 (1).svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_6.setIcon(icon2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.Login = QtWidgets.QPushButton(parent=self.welcomeLabel
)
        self.Login.setGeometry(QtCore.QRect(720, 10, 51, 31))
        self.Login.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"color: black;\n"
"")
        self.Login.setObjectName("Login")
        self.label_9 = QtWidgets.QLabel(parent=self.welcomeLabel
)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 61, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-10 121302.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.welcomeLabel = QtWidgets.QLabel(parent=self.welcomeLabel
)
        self.welcomeLabel.setGeometry(QtCore.QRect(110, 10, 241, 21))
        self.welcomeLabel.setStyleSheet("color:white;\n"
"font-size:10pt\n"
"")
        self.welcomeLabel.setObjectName("welcomeLabel")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Book.setText(_translate("MainWindow", "Book"))
        self.ksdds.setToolTip(_translate("MainWindow", "<html><head/><body><p><br/></p></body></html>"))
        self.ksdds.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>fgf</p></body></html>"))
        self.ksdds.setItemText(0, _translate("MainWindow", "Pick-up Address"))
        self.ksdds.setItemText(1, _translate("MainWindow", "Airport \"Manas\""))
        self.ksdds.setItemText(2, _translate("MainWindow", "Office \"PrimeCar\", Chokmorova 256"))
        self.comboBox.setItemText(0, _translate("MainWindow", "List of cars"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Hyundai Solaris"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Chevrolet Cobalt"))
        self.comboBox.setItemText(3, _translate("MainWindow", "Toyota Corolla"))
        self.comboBox.setItemText(4, _translate("MainWindow", "Hyundai Sonata"))
        self.comboBox.setItemText(5, _translate("MainWindow", "Toyota Rav 4"))
        self.comboBox.setItemText(6, _translate("MainWindow", "Subaru Forester"))
        self.comboBox.setItemText(7, _translate("MainWindow", "KIA Seltos 2024"))
        self.comboBox.setItemText(8, _translate("MainWindow", "Lexus RX330"))
        self.comboBox.setItemText(9, _translate("MainWindow", "Toyota 4Runner"))
        self.comboBox.setItemText(10, _translate("MainWindow", "Toyota Fortuner"))
        self.comboBox.setItemText(11, _translate("MainWindow", "Toyota Landcruiser 200"))
        self.comboBox.setItemText(12, _translate("MainWindow", "Lexus LX570"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Return address"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Airport \"Manas\""))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Office \"PrimeCar\", Chokmorova 256"))
        self.label_3.setText(_translate("MainWindow", "What class of car Do you need?"))
        self.Sedan.setText(_translate("MainWindow", "Sedan"))
        self.Crossover.setText(_translate("MainWindow", "Crossover"))
        self.SUV.setText(_translate("MainWindow", "SUV"))
        self.label_6.setText(_translate("MainWindow", "For city"))
        self.label_7.setText(_translate("MainWindow", "For city/highway"))
        self.label_8.setText(_translate("MainWindow", "For travel"))
        self.label.setText(_translate("MainWindow", "CAR RENTAL IN BISHKEK"))
        self.pushButton_6.setText(_translate("MainWindow", "+996773533969"))
        self.Login.setText(_translate("MainWindow", "Log in"))
        self.welcomeLabel.setText(_translate("MainWindow", "Hello, guest!"))
