# Form implementation generated from reading ui file 'registration.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(271, 394)
        self.frame = QtWidgets.QFrame(parent=Dialog)
        self.frame.setGeometry(QtCore.QRect(30, 10, 221, 391))
        self.frame.setStyleSheet("background-color:rgba(53,53,53,255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.Book = QtWidgets.QPushButton(parent=self.frame)
        self.Book.setGeometry(QtCore.QRect(10, 300, 200, 35))
        self.Book.setStyleSheet("background-color:Red;\n"
"font-size:15pt;\n"
"border-radius:7px\n"
"")
        self.Book.setObjectName("Book")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 100, 200, 25))
        self.comboBox_2.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.comboBox_2.setObjectName("comboBox_2")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icons/pin_drop_24dp_000000_FILL0_wght400_GRAD0_opsz24.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.comboBox_2.addItem(icon, "")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.dateTimeEdit_2 = QtWidgets.QDateTimeEdit(parent=self.frame)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(10, 60, 201, 31))
        self.dateTimeEdit_2.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.dateTimeEdit_2.setObjectName("dateTimeEdit_2")
        self.dateTimeEdit_3 = QtWidgets.QDateTimeEdit(parent=self.frame)
        self.dateTimeEdit_3.setGeometry(QtCore.QRect(10, 130, 201, 31))
        self.dateTimeEdit_3.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.dateTimeEdit_3.setObjectName("dateTimeEdit_3")
        self.comboBox = QtWidgets.QComboBox(parent=self.frame)
        self.comboBox.setGeometry(QtCore.QRect(10, 20, 201, 31))
        self.comboBox.setStyleSheet("background-color: white;\n"
"border-radius: 7px;\n"
"font-size: 9pt;\n"
"color: black;\n"
"")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Book.setText(_translate("Dialog", "Book"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Return address"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Airport \"Manas\""))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Office \"PrimeCar\", Chokmorova 256"))
        self.comboBox.setItemText(0, _translate("Dialog", "Pick up"))
        self.comboBox.setItemText(1, _translate("Dialog", "Airport \"Manas\""))
        self.comboBox.setItemText(2, _translate("Dialog", "Office \"PrimeCar\", Chokmorova 256"))
