# Form implementation generated from reading ui file 'suv.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog3(object):
    def setupUi(self, Dialog3):
        Dialog3.setObjectName("Dialog3")
        Dialog3.setEnabled(True)
        Dialog3.resize(701, 470)
        self.label = QtWidgets.QLabel(parent=Dialog3)
        self.label.setGeometry(QtCore.QRect(10, 0, 421, 41))
        self.label.setStyleSheet("font-weight:bold;\n"
"font-size:20pt")
        self.label.setObjectName("label")
        self.frame = QtWidgets.QFrame(parent=Dialog3)
        self.frame.setGeometry(QtCore.QRect(0, 50, 701, 431))
        self.frame.setStyleSheet("background-color:rgba(44,55,68,255)")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 151, 111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142729.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setGeometry(QtCore.QRect(370, 0, 151, 111))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142737.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setGeometry(QtCore.QRect(110, 210, 151, 111))
        self.label_4.setText("")
        self.label_4.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142746.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setGeometry(QtCore.QRect(370, 210, 151, 111))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../Pictures/Screenshots/Снимок экрана 2025-04-11 142811.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.frame)
        self.label_6.setGeometry(QtCore.QRect(110, 110, 191, 31))
        self.label_6.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.frame)
        self.label_7.setGeometry(QtCore.QRect(370, 115, 191, 21))
        self.label_7.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.frame)
        self.label_8.setGeometry(QtCore.QRect(110, 325, 231, 21))
        self.label_8.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.frame)
        self.label_9.setGeometry(QtCore.QRect(370, 325, 201, 21))
        self.label_9.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_9.setObjectName("label_9")
        self.Book = QtWidgets.QPushButton(parent=self.frame)
        self.Book.setGeometry(QtCore.QRect(110, 170, 141, 31))
        self.Book.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book.setObjectName("Book")
        self.Book2 = QtWidgets.QPushButton(parent=self.frame)
        self.Book2.setGeometry(QtCore.QRect(370, 170, 141, 31))
        self.Book2.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book2.setObjectName("Book2")
        self.Book3 = QtWidgets.QPushButton(parent=self.frame)
        self.Book3.setGeometry(QtCore.QRect(110, 380, 141, 31))
        self.Book3.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book3.setObjectName("Book3")
        self.Book4 = QtWidgets.QPushButton(parent=self.frame)
        self.Book4.setGeometry(QtCore.QRect(370, 380, 141, 31))
        self.Book4.setStyleSheet("color:white;\n"
"background-color:red;\n"
"font-size:15pt\n"
"")
        self.Book4.setObjectName("Book4")
        self.label_10 = QtWidgets.QLabel(parent=self.frame)
        self.label_10.setGeometry(QtCore.QRect(110, 145, 181, 21))
        self.label_10.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.frame)
        self.label_11.setGeometry(QtCore.QRect(110, 350, 191, 21))
        self.label_11.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.frame)
        self.label_12.setGeometry(QtCore.QRect(370, 350, 211, 21))
        self.label_12.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.frame)
        self.label_13.setGeometry(QtCore.QRect(370, 140, 181, 21))
        self.label_13.setStyleSheet("color:white;\n"
"font-size:13pt")
        self.label_13.setObjectName("label_13")

        self.retranslateUi(Dialog3)
        QtCore.QMetaObject.connectSlotsByName(Dialog3)

    def retranslateUi(self, Dialog3):
        _translate = QtCore.QCoreApplication.translate
        Dialog3.setWindowTitle(_translate("Dialog3", "SUV"))
        self.label.setText(_translate("Dialog3", "The list of SVU:"))
        self.label_6.setText(_translate("Dialog3", "Toyota Rav 4"))
        self.label_7.setText(_translate("Dialog3", "Toyota Fortuner"))
        self.label_8.setText(_translate("Dialog3", "Toyota Landcruiser 200"))
        self.label_9.setText(_translate("Dialog3", "Lexus LX570"))
        self.Book.setText(_translate("Dialog3", "Book"))
        self.Book2.setText(_translate("Dialog3", "Book"))
        self.Book3.setText(_translate("Dialog3", "Book"))
        self.Book4.setText(_translate("Dialog3", "Book"))
        self.label_10.setText(_translate("Dialog3", "5200-6500 KGS"))
        self.label_11.setText(_translate("Dialog3", "8000-10000 KGS"))
        self.label_12.setText(_translate("Dialog3", "9600-12000 KGS"))
        self.label_13.setText(_translate("Dialog3", "5600-7000 KGS"))
